// Danh mục dữ liệu nhân sự, phòng ban & tiêu chí đánh giá cho QTDND Yên Thọ

export const DEPARTMENTS = [
  'Ban Quản trị (HĐQT)',
  'Ban Điều hành',
  'Ban Kiểm soát',
  'Phòng Tín dụng',
  'Phòng Kế toán - Ngân quỹ',
];

export const ROLES = {
  STAFF: 'staff',
  MANAGER: 'manager',
  CHAIRMAN: 'chairman',
};

export const ROLE_LABELS = {
  [ROLES.STAFF]: 'Cán bộ',
  [ROLES.MANAGER]: 'Ban điều hành',
  [ROLES.CHAIRMAN]: 'Chủ tịch HĐQT',
};

// 10 Tiêu chí đánh giá tín nhiệm theo chuẩn nghiệp vụ Quỹ tín dụng nhân dân
export const TRUST_CRITERIA = [
  {
    id: 1,
    title: '1. Tinh thần trách nhiệm & Đạo đức nghề nghiệp',
    description: 'Tận tụy với công việc, trung thực, có trách nhiệm với nhiệm vụ được phân công, giữ gìn uy tín đơn vị.',
  },
  {
    id: 2,
    title: '2. Chấp hành Quy chế, Nội quy & Pháp luật NHNN',
    description: 'Nghiêm túc tuân thủ quy trình tín dụng, kế toán, an toàn kho quỹ và quy định của Ngân hàng Nhà nước.',
  },
  {
    id: 3,
    title: '3. Năng lực chuyên môn & Nghiệp vụ chuyên sâu',
    description: 'Nắm vững kiến thức chuyên môn, xử lý hồ sơ chuẩn xác, hạn chế tối đa sai sót trong giao dịch.',
  },
  {
    id: 4,
    title: '4. Tác phong giao dịch & Văn hóa phục vụ thành viên',
    description: 'Lịch thiệp, niềm nở, ân cần hỗ trợ thành viên và khách hàng, không gây phiền hà, sách nhiễu.',
  },
  {
    id: 5,
    title: '5. Tinh thần đoàn kết & Phối hợp phòng ban',
    description: 'Chủ động hợp tác, hỗ trợ đồng nghiệp, xây dựng khối đoàn kết nội bộ vững chắc.',
  },
  {
    id: 6,
    title: '6. Kỷ luật giờ giấc & Bảo mật thông tin tài chính',
    description: 'Đi làm đúng giờ, bảo quản tài liệu bảo mật, tuyệt đối không làm rò rỉ dữ liệu khách hàng.',
  },
  {
    id: 7,
    title: '7. Đổi mới sáng tạo & Ứng dụng công nghệ số',
    description: 'Tích cực học hỏi, áp dụng phần mềm quản lý, cải tiến quy trình tác nghiệp nhanh gọn.',
  },
  {
    id: 8,
    title: '8. Liêm chính tài chính & Phòng ngừa rủi ro đạo đức',
    description: 'Minh bạch trong tài chính, không nhận hối lộ, không tiếp tay cho các hành vi sai phạm tín dụng.',
  },
  {
    id: 9,
    title: '9. Đóng góp phong trào & Văn hóa tổ chức',
    description: 'Hăng hái tham gia các hoạt động xã hội, phong trào đoàn thể, xây dựng văn hóa QTDND thân thiện.',
  },
  {
    id: 10,
    title: '10. Hiệu quả hoàn thành chỉ tiêu công việc',
    description: 'Hoàn thành đúng tiến độ và chất lượng các chỉ tiêu kinh doanh, nghiệp vụ được giao phó.',
  },
];

// Danh sách nhân sự mẫu của Quỹ TDND Yên Thọ
export const INITIAL_EMPLOYEES = [
  {
    id: 'emp-001',
    code: 'CB01',
    name: 'Lê Đình Hải',
    email: 'chutich@qtdyentho.vn',
    role: ROLES.CHAIRMAN,
    department: 'Ban Quản trị (HĐQT)',
    position: 'Chủ tịch HĐQT',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    phone: '0912.345.678',
  },
  {
    id: 'emp-002',
    code: 'CB02',
    name: 'Trần Thị Mai',
    email: 'quanly@qtdyentho.vn',
    role: ROLES.MANAGER,
    department: 'Ban Điều hành',
    position: 'Giám đốc Điều hành',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    phone: '0988.765.432',
  },
  {
    id: 'emp-003',
    code: 'CB03',
    name: 'Nguyễn Văn An',
    email: 'canbo@qtdyentho.vn',
    role: ROLES.STAFF,
    department: 'Phòng Tín dụng',
    position: 'Cán bộ Tín dụng chính',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    phone: '0977.112.233',
  },
  {
    id: 'emp-004',
    code: 'CB04',
    name: 'Hoàng Minh Tuấn',
    email: 'tuan.hm@qtdyentho.vn',
    role: ROLES.STAFF,
    department: 'Phòng Tín dụng',
    position: 'Cán bộ Thẩm định',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    phone: '0943.556.789',
  },
  {
    id: 'emp-005',
    code: 'CB05',
    name: 'Phạm Thị Lan',
    email: 'lan.pt@qtdyentho.vn',
    role: ROLES.STAFF,
    department: 'Phòng Kế toán - Ngân quỹ',
    position: 'Kế toán trưởng',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    phone: '0936.889.900',
  },
  {
    id: 'emp-006',
    code: 'CB06',
    name: 'Bùi Thị Thanh',
    email: 'thanh.bt@qtdyentho.vn',
    role: ROLES.STAFF,
    department: 'Phòng Kế toán - Ngân quỹ',
    position: 'Thủ quỹ kiêm Giao dịch viên',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    phone: '0915.223.344',
  },
  {
    id: 'emp-007',
    code: 'CB07',
    name: 'Vũ Đức Nam',
    email: 'nam.vd@qtdyentho.vn',
    role: ROLES.STAFF,
    department: 'Ban Kiểm soát',
    position: 'Trưởng Ban Kiểm soát',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    phone: '0962.334.455',
  },
];

// Danh mục chức danh quy hoạch cán bộ nguồn
export const PLANNING_POSITIONS = [
  'Chủ tịch Hội đồng Quản trị',
  'Thành viên chuyên trách HĐQT',
  'Giám đốc Quỹ TDND',
  'Phó Giám đốc phụ trách Tín dụng',
  'Phó Giám đốc phụ trách Kế toán - Kho quỹ',
  'Trưởng Ban Kiểm soát',
  'Thành viên Ban Kiểm soát',
  'Kế toán trưởng',
  'Trưởng phòng Tín dụng',
];

// Dữ liệu mẫu ban đầu cho đánh giá tín nhiệm
export const INITIAL_TRUST_EVALUATIONS = [
  {
    id: 'trust-001',
    evaluatorId: 'emp-001',
    evaluatorName: 'Lê Đình Hải',
    evaluatorRole: 'chairman',
    targetEmployeeId: 'emp-003',
    targetEmployeeName: 'Nguyễn Văn An',
    targetDepartment: 'Phòng Tín dụng',
    scores: { 1: 9, 2: 9, 3: 9, 4: 10, 5: 9, 6: 9, 7: 8, 8: 10, 9: 9, 10: 9 },
    totalScore: 91,
    classification: 'Xuất sắc',
    notes: 'Cán bộ mẫu mực, hoàn thành vượt mức chỉ tiêu dư nợ 3 xã, quan hệ tốt với chính quyền và thành viên.',
    createdAt: '2026-09-15T09:30:00Z',
  },
  {
    id: 'trust-002',
    evaluatorId: 'emp-002',
    evaluatorName: 'Trần Thị Mai',
    evaluatorRole: 'manager',
    targetEmployeeId: 'emp-005',
    targetEmployeeName: 'Phạm Thị Lan',
    targetDepartment: 'Phòng Kế toán - Ngân quỹ',
    scores: { 1: 9, 2: 9, 3: 10, 4: 8, 5: 9, 6: 10, 7: 8, 8: 10, 9: 8, 10: 9 },
    totalScore: 90,
    classification: 'Xuất sắc',
    notes: 'Kế toán trưởng vững vàng nghiệp vụ, quyết toán tài chính chuẩn chỉ, cân đối thanh khoản an toàn.',
    createdAt: '2026-09-18T14:15:00Z',
  },
  {
    id: 'trust-003',
    evaluatorId: 'emp-002',
    evaluatorName: 'Trần Thị Mai',
    evaluatorRole: 'manager',
    targetEmployeeId: 'emp-004',
    targetEmployeeName: 'Hoàng Minh Tuấn',
    targetDepartment: 'Phòng Tín dụng',
    scores: { 1: 8, 2: 8, 3: 8, 4: 7, 5: 8, 6: 8, 7: 7, 8: 9, 9: 7, 10: 8 },
    totalScore: 78,
    classification: 'Tốt',
    notes: 'Thẩm định hồ sơ chặt chẽ, cần nâng cao tốc độ xử lý trên phần mềm tín dụng.',
    createdAt: '2026-09-22T10:00:00Z',
  },
  {
    id: 'trust-004',
    evaluatorId: 'emp-001',
    evaluatorName: 'Lê Đình Hải',
    evaluatorRole: 'chairman',
    targetEmployeeId: 'emp-006',
    targetEmployeeName: 'Bùi Thị Thanh',
    targetDepartment: 'Phòng Kế toán - Ngân quỹ',
    scores: { 1: 9, 2: 9, 3: 8, 4: 9, 5: 8, 6: 9, 7: 7, 8: 10, 9: 8, 10: 8 },
    totalScore: 85,
    classification: 'Tốt',
    notes: 'An toàn kho quỹ tuyệt đối, thái độ với khách hàng niềm nở, trung thực cao.',
    createdAt: '2026-09-25T16:20:00Z',
  },
  {
    id: 'trust-005',
    evaluatorId: 'emp-001',
    evaluatorName: 'Lê Đình Hải',
    evaluatorRole: 'chairman',
    targetEmployeeId: 'emp-007',
    targetEmployeeName: 'Vũ Đức Nam',
    targetDepartment: 'Ban Kiểm soát',
    scores: { 1: 9, 2: 10, 3: 9, 4: 8, 5: 8, 6: 10, 7: 8, 8: 10, 9: 8, 10: 9 },
    totalScore: 89,
    classification: 'Tốt',
    notes: 'Kiểm tra độc lập, kịp thời kiến nghị các điểm cần khắc phục trong quy trình.',
    createdAt: '2026-09-28T11:45:00Z',
  },
];

// Dữ liệu mẫu ban đầu cho KPI
export const INITIAL_KPI_EVALUATIONS = [
  {
    id: 'kpi-001',
    period: 'Quý III / 2026',
    employeeId: 'emp-003',
    employeeName: 'Nguyễn Văn An',
    department: 'Phòng Tín dụng',
    position: 'Cán bộ Tín dụng chính',
    scoreSelf: 92,
    scoreManager: 90,
    scoreChairman: 94,
    finalScore: 92.0, // (92 * 0.4) + (90 * 0.3) + (94 * 0.3) = 36.8 + 27.0 + 28.2 = 92.0
    status: 'completed', // 'pending_manager' | 'pending_chairman' | 'completed'
    selfNotes: 'Hoàn thành 110% chỉ tiêu tăng trưởng dư nợ Quý 3, không phát sinh nợ quá hạn mới.',
    managerNotes: 'Đánh giá cao nỗ lực bám sát các thôn bản và xử lý hồ sơ chu đáo.',
    chairmanNotes: 'Thống nhất xếp loại thi đua mức cao nhất quý này.',
    updatedAt: '2026-09-30T17:00:00Z',
  },
  {
    id: 'kpi-002',
    period: 'Quý III / 2026',
    employeeId: 'emp-005',
    employeeName: 'Phạm Thị Lan',
    department: 'Phòng Kế toán - Ngân quỹ',
    position: 'Kế toán trưởng',
    scoreSelf: 88,
    scoreManager: 92,
    scoreChairman: 90,
    finalScore: 89.8, // (88 * 0.4) + (92 * 0.3) + (90 * 0.3) = 35.2 + 27.6 + 27.0 = 89.8
    status: 'completed',
    selfNotes: 'Báo cáo NHNN đúng hạn, hạch toán chính xác 100%, bảo đảm thanh khoản.',
    managerNotes: 'Quản trị dòng vốn hiệu quả, chi trả lương và huy động nhịp nhàng.',
    chairmanNotes: 'Hoàn thành xuất sắc nhiệm vụ.',
    updatedAt: '2026-09-30T17:10:00Z',
  },
  {
    id: 'kpi-003',
    period: 'Quý III / 2026',
    employeeId: 'emp-004',
    employeeName: 'Hoàng Minh Tuấn',
    department: 'Phòng Tín dụng',
    position: 'Cán bộ Thẩm định',
    scoreSelf: 85,
    scoreManager: 80,
    scoreChairman: null,
    finalScore: null,
    status: 'pending_chairman',
    selfNotes: 'Đã thẩm định 45 hồ sơ vay vốn, tỷ lệ hồ sơ hợp lệ đạt 98%.',
    managerNotes: 'Cần chú ý đối soát thực địa các tài sản bảo đảm là đất nông nghiệp.',
    chairmanNotes: '',
    updatedAt: '2026-10-02T10:15:00Z',
  },
  {
    id: 'kpi-004',
    period: 'Quý III / 2026',
    employeeId: 'emp-006',
    employeeName: 'Bùi Thị Thanh',
    department: 'Phòng Kế toán - Ngân quỹ',
    position: 'Thủ quỹ kiêm Giao dịch viên',
    scoreSelf: 86,
    scoreManager: null,
    scoreChairman: null,
    finalScore: null,
    status: 'pending_manager',
    selfNotes: 'Thu chi tiền mặt khớp số liệu 100%, phục vụ 650 lượt giao dịch an toàn.',
    managerNotes: '',
    chairmanNotes: '',
    updatedAt: '2026-10-05T08:30:00Z',
  },
];

// Dữ liệu mẫu ban đầu cho Bỏ phiếu quy hoạch cán bộ
export const INITIAL_PLANNING_VOTES = [
  {
    id: 'vote-001',
    voterId: 'emp-001',
    voterName: 'Lê Đình Hải',
    voterRole: 'chairman',
    candidateId: 'emp-003',
    candidateName: 'Nguyễn Văn An',
    currentPosition: 'Cán bộ Tín dụng chính',
    department: 'Phòng Tín dụng',
    proposedRole: 'Phó Giám đốc phụ trách Tín dụng',
    vote: 'Tín nhiệm cao',
    comments: 'Đồng chí có phẩm chất đạo đức tốt, có năng lực chỉ đạo mảng tín dụng cơ sở, uy tín cao trong tập thể.',
    createdAt: '2026-09-20T15:00:00Z',
  },
  {
    id: 'vote-002',
    voterId: 'emp-002',
    voterName: 'Trần Thị Mai',
    voterRole: 'manager',
    candidateId: 'emp-003',
    candidateName: 'Nguyễn Văn An',
    currentPosition: 'Cán bộ Tín dụng chính',
    department: 'Phòng Tín dụng',
    proposedRole: 'Phó Giám đốc phụ trách Tín dụng',
    vote: 'Tín nhiệm cao',
    comments: 'Rất nhất trí, đồng chí An năng động, trách nhiệm và có năng lực quy tụ nhân sự.',
    createdAt: '2026-09-21T09:40:00Z',
  },
  {
    id: 'vote-003',
    voterId: 'emp-001',
    voterName: 'Lê Đình Hải',
    voterRole: 'chairman',
    candidateId: 'emp-005',
    candidateName: 'Phạm Thị Lan',
    currentPosition: 'Kế toán trưởng',
    department: 'Phòng Kế toán - Ngân quỹ',
    proposedRole: 'Phó Giám đốc phụ trách Kế toán - Kho quỹ',
    vote: 'Tín nhiệm cao',
    comments: 'Am hiểu sâu nghiệp vụ tài chính tiền tệ, bảo đảm an toàn hệ thống.',
    createdAt: '2026-09-22T14:10:00Z',
  },
  {
    id: 'vote-004',
    voterId: 'emp-002',
    voterName: 'Trần Thị Mai',
    voterRole: 'manager',
    candidateId: 'emp-004',
    candidateName: 'Hoàng Minh Tuấn',
    currentPosition: 'Cán bộ Thẩm định',
    department: 'Phòng Tín dụng',
    proposedRole: 'Trưởng phòng Tín dụng',
    vote: 'Tín nhiệm',
    comments: 'Cán bộ trẻ có nhiệt huyết, cần thêm thời gian thử thách rèn luyện bản lĩnh quản lý.',
    createdAt: '2026-09-24T16:30:00Z',
  },
];
