// Danh mục dữ liệu chuẩn hóa: Nhân sự, Phòng ban, Luân chuyển công tác & Tiêu chí Đánh giá Tín nhiệm
// Áp dụng cho Quỹ Tín Dụng Nhân Dân Yên Thọ (Thanh Hóa)

export const DEPARTMENTS = [
  'Ban Quản trị (HĐQT)',
  'Ban Điều hành',
  'Ban Kiểm soát',
  'Phòng Tín dụng',
  'Phòng Kế toán - Ngân quỹ',
];

export const ROLES = {
  STAFF: 'staff',
  MANAGER: 'manager',
  CHAIRMAN: 'chairman',
};

export const ROLE_LABELS = {
  [ROLES.STAFF]: 'Cán bộ',
  [ROLES.MANAGER]: 'Ban điều hành',
  [ROLES.CHAIRMAN]: 'Chủ tịch HĐQT',
};

// ============================================================================
// 1. DANH MỤC 10 TIÊU CHÍ ĐÁNH GIÁ TÍN NHIỆM CHUẨN MỰC
// ============================================================================
export const TRUST_CRITERIA = [
  {
    id: 1,
    code: 'TC01',
    group: 'Phẩm chất đạo đức',
    title: '1. Tinh thần trách nhiệm & Đạo đức nghề nghiệp',
    description: 'Tận tụy với công việc, trung thực, có tinh thần trách nhiệm cao, giữ gìn và phát huy uy tín thương hiệu của Quỹ.',
    maxScore: 10,
    minScore: 0,
  },
  {
    id: 2,
    code: 'TC02',
    group: 'Tuân thủ pháp luật & Quy chế',
    title: '2. Chấp hành Quy chế, Nội quy & Pháp luật NHNN',
    description: 'Nghiêm túc tuân thủ quy trình tín dụng, kế toán, an toàn kho quỹ và các văn bản chỉ đạo của Ngân hàng Nhà nước.',
    maxScore: 10,
    minScore: 0,
  },
  {
    id: 3,
    code: 'TC03',
    group: 'Năng lực chuyên môn',
    title: '3. Năng lực chuyên môn & Nghiệp vụ chuyên sâu',
    description: 'Nắm vững quy trình nghiệp vụ, xử lý hồ sơ nhanh chóng, chuẩn xác, hạn chế tối đa sai sót rủi ro vận hành.',
    maxScore: 10,
    minScore: 0,
  },
  {
    id: 4,
    code: 'TC04',
    group: 'Văn hóa giao dịch',
    title: '4. Tác phong giao dịch & Văn hóa phục vụ thành viên',
    description: 'Ân cần, niềm nở, lịch thiệp khi tiếp xúc thành viên và khách hàng vay/gửi vốn, không quan liêu, hách dịch.',
    maxScore: 10,
    minScore: 0,
  },
  {
    id: 5,
    code: 'TC05',
    group: 'Xây dựng tập thể',
    title: '5. Tinh thần đoàn kết & Phối hợp phòng ban',
    description: 'Tương trợ đồng nghiệp, phối hợp nhịp nhàng giữa Tín dụng, Kế toán, Kiểm soát và Ban điều hành.',
    maxScore: 10,
    minScore: 0,
  },
  {
    id: 6,
    code: 'TC06',
    group: 'Kỷ luật & Bảo mật',
    title: '6. Kỷ luật giờ giấc & Bảo mật thông tin tài chính',
    description: 'Chấp hành thời giờ làm việc, bảo quản tài liệu lưu trữ, giữ bí mật tuyệt đối số dư tiền gửi và hồ sơ khách hàng.',
    maxScore: 10,
    minScore: 0,
  },
  {
    id: 7,
    code: 'TC07',
    group: 'Đổi mới & Cải tiến',
    title: '7. Đổi mới sáng tạo & Chuyển đổi số',
    description: 'Chủ động làm chủ phần mềm quản lý, ứng dụng công nghệ trong tác nghiệp, có giải pháp cải tiến hiệu quả.',
    maxScore: 10,
    minScore: 0,
  },
  {
    id: 8,
    code: 'TC08',
    group: 'Liêm chính tài chính',
    title: '8. Liêm chính tài chính & Phòng ngừa rủi ro đạo đức',
    description: 'Minh bạch tiền tệ, tuyệt đối không vòi vĩnh chi phí ngoài quy định, không thông đồng trục lợi tín dụng.',
    maxScore: 10,
    minScore: 0,
  },
  {
    id: 9,
    code: 'TC09',
    group: 'Phong trào đơn vị',
    title: '9. Đóng góp phong trào & Văn hóa tổ chức',
    description: 'Nhiệt tình tham gia các hoạt động an sinh xã hội, phong trào công đoàn, xây dựng đơn vị vững mạnh.',
    maxScore: 10,
    minScore: 0,
  },
  {
    id: 10,
    code: 'TC10',
    group: 'Kết quả công tác',
    title: '10. Hiệu quả hoàn thành chỉ tiêu công việc',
    description: 'Hoàn thành và hoàn thành vượt mức các chỉ tiêu được giao về dư nợ, huy động vốn, kiểm soát nợ quá hạn.',
    maxScore: 10,
    minScore: 0,
  },
];

// ============================================================================
// 2. DANH MỤC KỲ / ĐỢT ĐÁNH GIÁ TÍN NHIỆM
// ============================================================================
export const EVALUATION_PERIODS = [
  {
    id: 'PERIOD-2026-Q3',
    name: 'Đánh giá tín nhiệm Quý III / 2026',
    year: 2026,
    quarter: 3,
    votingMode: 'OPTIONAL', // 'ANONYMOUS_ONLY' | 'IDENTIFIED_ONLY' | 'OPTIONAL'
    status: 'ACTIVE',
    startDate: '2026-09-15',
    endDate: '2026-10-15',
  },
  {
    id: 'PERIOD-2026-Q4',
    name: 'Đánh giá tín nhiệm & Thi đua Quý IV / 2026',
    year: 2026,
    quarter: 4,
    votingMode: 'ANONYMOUS_ONLY', // Bỏ phiếu kín 100%
    status: 'UPCOMING',
    startDate: '2026-12-01',
    endDate: '2026-12-31',
  },
];

// ============================================================================
// 3. HỒ SƠ CÁN BỘ NHÂN VIÊN CHI TIẾT (EMPLOYEES / USERS)
// ============================================================================
export const INITIAL_EMPLOYEES = [
  {
    id: 'emp-001',
    order: 1,
    code: 'CB01',
    name: 'Nguyễn Thị Sinh',
    gender: 'Nữ',
    birthDate: '',
    cccd: '038162004401',
    email: 'Sinhtdyt@gmail.com',
    role: ROLES.STAFF,
    department: 'Phòng Tín dụng',
    position: 'Thẩm định tài sản',
    assignedArea: 'Bộ phận Thẩm định tài sản & Hồ sơ vay vốn',
    partyMember: true,
    politicalRole: 'Đảng viên',
    partyDate: '2005-03-09',
    partyOfficialDate: '2006-03-09',
    education: 'Chờ bổ sung',
    joinDate: '2005-03-09',
    contractType: 'Không xác định thời hạn',
    status: 'ACTIVE',
    phone: '0388232844',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-002',
    order: 2,
    code: 'CB02',
    name: 'Nguyễn Thị Mến',
    gender: 'Nữ',
    birthDate: '',
    cccd: '038183010925',
    email: 'nguyenmen.yt.83@gmail.com',
    role: ROLES.MANAGER,
    department: 'Phòng Kế toán - Ngân quỹ',
    position: 'Kế toán trưởng',
    assignedArea: 'Phụ trách toàn diện Kế toán, Tài chính & Ngân quỹ',
    partyMember: true,
    politicalRole: 'Đảng viên',
    partyDate: '2007-03-09',
    partyOfficialDate: '2008-03-08',
    education: 'Chờ bổ sung',
    joinDate: '2007-03-09',
    contractType: 'Không xác định thời hạn',
    status: 'ACTIVE',
    phone: '0349547779',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-003',
    order: 3,
    code: 'CB03',
    name: 'Nguyễn Văn Sơn',
    gender: 'Nam',
    birthDate: '',
    cccd: '038080021750',
    email: 'nguyenvansontdyt@gmail.com',
    role: ROLES.MANAGER,
    department: 'Ban Điều hành',
    position: 'UV HĐQT - Giám đốc',
    assignedArea: 'Điều hành toàn diện hoạt động kinh doanh Quỹ',
    partyMember: true,
    politicalRole: 'Phó Bí thư Chi bộ',
    partyDate: '2012-10-09',
    partyOfficialDate: '2013-10-09',
    education: 'Chờ bổ sung',
    joinDate: '2012-10-09',
    contractType: 'Theo nhiệm kỳ bổ nhiệm',
    status: 'ACTIVE',
    phone: '0941562789',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-004',
    order: 4,
    code: 'CB04',
    name: 'Bùi Thị Thảo',
    gender: 'Nữ',
    birthDate: '',
    cccd: '038182047645',
    email: 'thao.bui0282@gmail.com',
    role: ROLES.MANAGER,
    department: 'Ban Kiểm soát',
    position: 'Trưởng ban kiểm soát',
    assignedArea: 'Kiểm soát nội bộ toàn diện hoạt động Quỹ',
    partyMember: true,
    politicalRole: 'Đảng viên',
    partyDate: '2012-11-19',
    partyOfficialDate: '2013-11-19',
    education: 'Chờ bổ sung',
    joinDate: '2012-11-19',
    contractType: 'Theo nhiệm kỳ Đại hội',
    status: 'ACTIVE',
    phone: '0839062825',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-005',
    order: 5,
    code: 'CB05',
    name: 'Nguyễn Hữu Nhân',
    gender: 'Nam',
    birthDate: '',
    cccd: '038085009285',
    email: 'qtdyentho.huunhan@gmail.com',
    role: ROLES.STAFF,
    department: 'Phòng Tín dụng',
    position: 'CB tín dụng',
    assignedArea: 'Quản lý khách hàng & phát triển tín dụng',
    partyMember: true,
    politicalRole: 'Đảng viên',
    partyDate: '2013-01-30',
    partyOfficialDate: '2014-01-30',
    education: 'Chờ bổ sung',
    joinDate: '2013-01-30',
    contractType: 'Không xác định thời hạn',
    status: 'ACTIVE',
    phone: '0949116817',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-006',
    order: 6,
    code: 'CB06',
    name: 'Trịnh Thị Hiền',
    gender: 'Nữ',
    birthDate: '',
    cccd: '038183049074',
    email: 'qtdyentho.hienha@gmail.com',
    role: ROLES.STAFF,
    department: 'Ban Kiểm soát',
    position: 'KST - Kiểm toán nội bộ',
    assignedArea: 'Kiểm soát tài chính & kiểm toán nội bộ',
    partyMember: true,
    politicalRole: 'Đảng viên',
    partyDate: '2014-05-21',
    partyOfficialDate: '2015-05-21',
    education: 'Chờ bổ sung',
    joinDate: '2014-05-21',
    contractType: 'Không xác định thời hạn',
    status: 'ACTIVE',
    phone: '0948784333',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-007',
    order: 7,
    code: 'CB07',
    name: 'Trịnh Đức Anh',
    gender: 'Nam',
    birthDate: '',
    cccd: '038086010115',
    email: 'ducanht@gmail.com',
    role: ROLES.CHAIRMAN,
    department: 'Ban Quản trị (HĐQT)',
    position: 'Chủ tịch HĐQT',
    assignedArea: 'Lãnh đạo toàn diện HĐQT & Định hướng chiến lược Quỹ',
    partyMember: true,
    politicalRole: 'Bí thư Chi bộ',
    partyDate: '2016-06-03',
    partyOfficialDate: '2017-06-03',
    education: 'Chờ bổ sung',
    joinDate: '2016-06-03',
    contractType: 'Theo nhiệm kỳ Đại hội',
    status: 'ACTIVE',
    phone: '0965122111',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-008',
    order: 8,
    code: 'CB08',
    name: 'Vũ Thị Hiền',
    gender: 'Nữ',
    birthDate: '',
    cccd: '038186037786',
    email: 'qtdyentho.vuhien@gmail.com',
    role: ROLES.CHAIRMAN,
    department: 'Ban Quản trị (HĐQT)',
    position: 'UV HĐQT',
    assignedArea: 'Ủy viên Hội đồng Quản trị',
    partyMember: true,
    politicalRole: 'Đảng viên',
    partyDate: '2018-06-04',
    partyOfficialDate: '2019-06-04',
    education: 'Chờ bổ sung',
    joinDate: '2018-06-04',
    contractType: 'Theo nhiệm kỳ Đại hội',
    status: 'ACTIVE',
    phone: '0983502181',
    avatar: 'https://images.unsplash.com/photo-1548142813-c348350df52b?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-009',
    order: 9,
    code: 'CB09',
    name: 'Trần Như Huyền',
    gender: 'Nữ',
    birthDate: '',
    cccd: '038189039532',
    email: 'Huyennhutran@gmail.com',
    role: ROLES.STAFF,
    department: 'Phòng Tín dụng',
    position: 'CB tín dụng',
    assignedArea: 'Quản lý khách hàng vay & thẩm định tín dụng',
    partyMember: true,
    politicalRole: 'Đảng viên',
    partyDate: '2020-12-11',
    partyOfficialDate: '2021-12-11',
    education: 'Chờ bổ sung',
    joinDate: '2020-12-11',
    contractType: 'Không xác định thời hạn',
    status: 'ACTIVE',
    phone: '0985709609',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-010',
    order: 10,
    code: 'CB10',
    name: 'Hoàng Thị Lan',
    gender: 'Nữ',
    birthDate: '',
    cccd: '038189040044',
    email: 'hoanglan1289@gmail.com',
    role: ROLES.STAFF,
    department: 'Phòng Kế toán - Ngân quỹ',
    position: 'Kế toán viên',
    assignedArea: 'Hạch toán kế toán, thanh toán & đối soát',
    partyMember: true,
    politicalRole: 'Đảng viên',
    partyDate: '2021-10-08',
    partyOfficialDate: '2022-10-08',
    education: 'Chờ bổ sung',
    joinDate: '2021-10-08',
    contractType: 'Không xác định thời hạn',
    status: 'ACTIVE',
    phone: '0965178666',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-011',
    order: 11,
    code: 'CB11',
    name: 'Phạm Thị Thảo',
    gender: 'Nữ',
    birthDate: '',
    cccd: '038190051894',
    email: 'qtdyentho.phamthao@gmail.com',
    role: ROLES.STAFF,
    department: 'Phòng Kế toán - Ngân quỹ',
    position: 'Thủ quỹ',
    assignedArea: 'Quản lý kho quỹ, tiền mặt & thu chi tại quầy',
    partyMember: true,
    politicalRole: 'Đảng viên',
    partyDate: '2023-09-06',
    partyOfficialDate: '2024-09-06',
    education: 'Chờ bổ sung',
    joinDate: '2023-09-06',
    contractType: 'Không xác định thời hạn',
    status: 'ACTIVE',
    phone: '0965567596',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-012',
    order: 12,
    code: 'CB12',
    name: 'Lưu Thị Định',
    gender: 'Nữ',
    birthDate: '',
    cccd: '038189028302',
    email: 'qtdyentho.luudinh@gmail.com',
    role: ROLES.STAFF,
    department: 'Phòng Tín dụng',
    position: 'CB tín dụng',
    assignedArea: 'Quản lý khách hàng vay & thẩm định địa bàn',
    partyMember: true,
    politicalRole: 'Đảng viên',
    partyDate: '2024-09-06',
    partyOfficialDate: '2025-09-06',
    education: 'Chờ bổ sung',
    joinDate: '2024-09-06',
    contractType: 'Không xác định thời hạn',
    status: 'ACTIVE',
    phone: '0961007855',
    avatar: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=150&auto=format&fit=crop&q=80',
  },
];

// ============================================================================
// 4. QUÁ TRÌNH LUÂN CHUYỂN CÔNG TÁC CỦA CÁN BỘ (WORK_HISTORY)
// ============================================================================
export const INITIAL_WORK_HISTORY = [
  {
    id: 'trans-001',
    employeeId: 'emp-005',
    employeeCode: 'CB05',
    employeeName: 'Nguyễn Hữu Nhân',
    decisionNumber: '24/QĐ-HĐQT-2022',
    decisionDate: '2022-08-10',
    effectiveDate: '2022-08-15',
    transferType: 'LUAN_CHUYEN_DINH_KY',
    transferTypeLabel: 'Luân chuyển định kỳ địa bàn tín dụng',
    fromDepartment: 'Phòng Tín dụng',
    toDepartment: 'Phòng Tín dụng',
    fromPosition: 'Cán bộ Tín dụng phụ trách cụm thôn',
    toPosition: 'Cán bộ Tín dụng chính phụ trách địa bàn Yên Thọ',
    fromAssignedArea: 'Cụm thôn xã Quý Lộc',
    toAssignedArea: 'Toàn địa bàn xã Yên Thọ',
    signer: 'Trịnh Đức Anh (Chủ tịch HĐQT)',
    reason: 'Thực hiện quy định NHNN về luân chuyển định kỳ cán bộ tín dụng sau 3 năm.',
    handoverStatus: 'DA_BAN_GIAO',
    notes: 'Đã hoàn tất bàn giao hồ sơ tín dụng và tài sản bảo đảm.',
  },
  {
    id: 'trans-002',
    employeeId: 'emp-002',
    employeeCode: 'CB02',
    employeeName: 'Nguyễn Thị Mến',
    decisionNumber: '08/QĐ-HĐQT-2020',
    decisionDate: '2020-03-12',
    effectiveDate: '2020-04-01',
    transferType: 'BO_NHIEM',
    transferTypeLabel: 'Bổ nhiệm Kế toán trưởng',
    fromDepartment: 'Phòng Kế toán - Ngân quỹ',
    toDepartment: 'Phòng Kế toán - Ngân quỹ',
    fromPosition: 'Kế toán viên chính',
    toPosition: 'Kế toán trưởng Quỹ TDND',
    fromAssignedArea: 'Hạch toán kế toán',
    toAssignedArea: 'Phụ trách toàn diện Kế toán & Ngân quỹ',
    signer: 'Trịnh Đức Anh (Chủ tịch HĐQT)',
    reason: 'Đạt chuẩn chức danh Kế toán trưởng theo phê chuẩn của NHNN Chi nhánh tỉnh Thanh Hóa.',
    handoverStatus: 'DA_BAN_GIAO',
    notes: 'Tiếp nhận bàn giao chứng từ và chữ ký số kế toán trưởng.',
  },
  {
    id: 'trans-003',
    employeeId: 'emp-011',
    employeeCode: 'CB11',
    employeeName: 'Phạm Thị Thảo',
    decisionNumber: '15/QĐ-HĐQT-2023',
    decisionDate: '2023-08-25',
    effectiveDate: '2023-09-06',
    transferType: 'BO_NHIEM',
    transferTypeLabel: 'Bổ nhiệm Thủ quỹ',
    fromDepartment: 'Phòng Kế toán - Ngân quỹ',
    toDepartment: 'Phòng Kế toán - Ngân quỹ',
    fromPosition: 'Nhân viên ngân quỹ tập sự',
    toPosition: 'Thủ quỹ Quỹ TDND',
    fromAssignedArea: 'Tập sự kho quỹ',
    toAssignedArea: 'Quản lý két sắt, tiền mặt và thu chi tại quầy',
    signer: 'Nguyễn Văn Sơn (Giám đốc)',
    reason: 'Hoàn thành thời gian tập sự nghiệp vụ kho quỹ an toàn.',
    handoverStatus: 'DA_BAN_GIAO',
    notes: 'Kiểm kê bàn giao két sắt và sổ quỹ tiền mặt.',
  },
  {
    id: 'trans-004',
    employeeId: 'emp-001',
    employeeCode: 'CB01',
    employeeName: 'Nguyễn Thị Sinh',
    decisionNumber: '19/QĐ-HĐQT-2021',
    decisionDate: '2021-05-10',
    effectiveDate: '2021-06-01',
    transferType: 'PHAN_CONG_CHUYEN_TRACH',
    transferTypeLabel: 'Phân công chuyên trách Thẩm định tài sản',
    fromDepartment: 'Phòng Tín dụng',
    toDepartment: 'Phòng Tín dụng',
    fromPosition: 'Cán bộ Tín dụng',
    toPosition: 'Cán bộ chuyên trách Thẩm định tài sản',
    fromAssignedArea: 'Địa bàn tín dụng',
    toAssignedArea: 'Thẩm định giá trị đất đai, nhà ở & tài sản thế chấp',
    signer: 'Trịnh Đức Anh (Chủ tịch HĐQT)',
    reason: 'Kiện toàn tổ thẩm định độc lập theo định hướng quản trị rủi ro của Quỹ.',
    handoverStatus: 'DA_BAN_GIAO',
    notes: 'Bàn giao các hồ sơ tín dụng quản lý trước đó.',
  },
];

// Danh mục chức danh quy hoạch cán bộ nguồn
export const PLANNING_POSITIONS = [
  'Chủ tịch Hội đồng Quản trị',
  'Thành viên chuyên trách HĐQT',
  'Giám đốc Quỹ TDND',
  'Phó Giám đốc phụ trách Tín dụng',
  'Phó Giám đốc phụ trách Kế toán - Kho quỹ',
  'Trưởng Ban Kiểm soát',
  'Thành viên Ban Kiểm soát',
  'Kế toán trưởng',
  'Trưởng phòng Tín dụng',
];

// ============================================================================
// 5. PHIẾU ĐÁNH GIÁ TÍN NHIỆM MẪU (EVALUATIONS_TRUST) - HỖ TRỢ ẨN DANH / CÔNG KHAI
// ============================================================================
export const INITIAL_TRUST_EVALUATIONS = [
  {
    id: 'trust-001',
    periodId: 'PERIOD-2026-Q3',
    periodName: 'Đánh giá tín nhiệm Quý III / 2026',
    isAnonymous: false,
    evaluatorId: 'emp-007',
    evaluatorName: 'Trịnh Đức Anh',
    evaluatorRole: 'chairman',
    targetEmployeeId: 'emp-005',
    targetEmployeeCode: 'CB05',
    targetEmployeeName: 'Nguyễn Hữu Nhân',
    targetDepartment: 'Phòng Tín dụng',
    scores: { 1: 9, 2: 9, 3: 9, 4: 10, 5: 9, 6: 9, 7: 8, 8: 10, 9: 9, 10: 9 },
    totalScore: 91,
    classification: 'Xuất sắc',
    notes: 'Cán bộ mẫu mực, hoàn thành tốt chỉ tiêu tín dụng, tuân thủ nghiêm ngặt quy trình quản trị rủi ro.',
    createdAt: '2026-09-15T09:30:00Z',
  },
  {
    id: 'trust-002',
    periodId: 'PERIOD-2026-Q3',
    periodName: 'Đánh giá tín nhiệm Quý III / 2026',
    isAnonymous: true,
    evaluatorId: 'emp-003',
    evaluatorName: 'Cán bộ Quỹ (Ẩn danh)',
    evaluatorRole: 'Ẩn danh',
    targetEmployeeId: 'emp-002',
    targetEmployeeCode: 'CB02',
    targetEmployeeName: 'Nguyễn Thị Mến',
    targetDepartment: 'Phòng Kế toán - Ngân quỹ',
    scores: { 1: 9, 2: 9, 3: 10, 4: 9, 5: 9, 6: 10, 7: 8, 8: 10, 9: 9, 10: 9 },
    totalScore: 92,
    classification: 'Xuất sắc',
    notes: 'Kế toán trưởng vững vàng chuyên môn, sổ sách kế toán chuẩn mực, thanh khoản vững vàng.',
    createdAt: '2026-09-18T14:15:00Z',
  },
  {
    id: 'trust-003',
    periodId: 'PERIOD-2026-Q3',
    periodName: 'Đánh giá tín nhiệm Quý III / 2026',
    isAnonymous: false,
    evaluatorId: 'emp-003',
    evaluatorName: 'Nguyễn Văn Sơn',
    evaluatorRole: 'manager',
    targetEmployeeId: 'emp-001',
    targetEmployeeCode: 'CB01',
    targetEmployeeName: 'Nguyễn Thị Sinh',
    targetDepartment: 'Phòng Tín dụng',
    scores: { 1: 9, 2: 9, 3: 9, 4: 9, 5: 9, 6: 9, 7: 9, 8: 9, 9: 9, 10: 9 },
    totalScore: 90,
    classification: 'Xuất sắc',
    notes: 'Thẩm định hồ sơ chặt chẽ, chính xác, không để phát sinh rủi ro tài sản bảo đảm.',
    createdAt: '2026-09-20T10:00:00Z',
  },
  {
    id: 'trust-004',
    periodId: 'PERIOD-2026-Q3',
    periodName: 'Đánh giá tín nhiệm Quý III / 2026',
    isAnonymous: false,
    evaluatorId: 'emp-007',
    evaluatorName: 'Trịnh Đức Anh',
    evaluatorRole: 'chairman',
    targetEmployeeId: 'emp-011',
    targetEmployeeCode: 'CB11',
    targetEmployeeName: 'Phạm Thị Thảo',
    targetDepartment: 'Phòng Kế toán - Ngân quỹ',
    scores: { 1: 9, 2: 9, 3: 8, 4: 9, 5: 8, 6: 9, 7: 7, 8: 10, 9: 8, 10: 8 },
    totalScore: 85,
    classification: 'Tốt',
    notes: 'An toàn kho quỹ tuyệt đối, thái độ với khách hàng niềm nở, trung thực cao.',
    createdAt: '2026-09-25T16:20:00Z',
  },
  {
    id: 'trust-005',
    periodId: 'PERIOD-2026-Q3',
    periodName: 'Đánh giá tín nhiệm Quý III / 2026',
    isAnonymous: true,
    evaluatorId: 'emp-002',
    evaluatorName: 'Cán bộ Quỹ (Ẩn danh)',
    evaluatorRole: 'Ẩn danh',
    targetEmployeeId: 'emp-004',
    targetEmployeeCode: 'CB04',
    targetEmployeeName: 'Bùi Thị Thảo',
    targetDepartment: 'Ban Kiểm soát',
    scores: { 1: 9, 2: 10, 3: 9, 4: 8, 5: 8, 6: 10, 7: 8, 8: 10, 9: 8, 10: 9 },
    totalScore: 89,
    classification: 'Tốt',
    notes: 'Kiểm tra độc lập, kịp thời kiến nghị các điểm cần khắc phục trong quy trình.',
    createdAt: '2026-09-28T11:45:00Z',
  },
];

// ============================================================================
// 6. DỮ LIỆU KPI MẪU (EVALUATIONS_KPI)
// ============================================================================
export const INITIAL_KPI_EVALUATIONS = [
  {
    id: 'kpi-2026-Q3-emp-005',
    period: 'Quý III / 2026',
    employeeId: 'emp-005',
    employeeCode: 'CB05',
    employeeName: 'Nguyễn Hữu Nhân',
    department: 'Phòng Tín dụng',
    position: 'CB tín dụng',
    scoreSelf: 88,
    scoreManager: 90,
    scoreChairman: 92,
    finalScore: 90,
    classification: 'Xuất sắc',
    status: 'completed',
    selfNotes: 'Hoàn thành 102% kế hoạch tăng trưởng dư nợ và kiểm soát nợ quá hạn 0%.',
    managerNotes: 'Tác phong nghiệp vụ tốt, chịu khó bám sát thành viên vay vốn.',
    chairmanNotes: 'Biểu dương tinh thần trách nhiệm và kết quả dư nợ an toàn.',
    updatedAt: '2026-09-28T16:00:00Z',
  },
  {
    id: 'kpi-2026-Q3-emp-001',
    period: 'Quý III / 2026',
    employeeId: 'emp-001',
    employeeCode: 'CB01',
    employeeName: 'Nguyễn Thị Sinh',
    department: 'Phòng Tín dụng',
    position: 'Thẩm định tài sản',
    scoreSelf: 86,
    scoreManager: 88,
    scoreChairman: 88,
    finalScore: 87.2,
    classification: 'Tốt',
    status: 'completed',
    selfNotes: 'Thẩm định 100% hồ sơ đúng hạn, kiểm tra hiện trạng tài sản nghiêm túc.',
    managerNotes: 'Hồ sơ thẩm định đầy đủ căn cứ pháp lý.',
    chairmanNotes: 'Thống nhất kết quả xếp loại Tốt.',
    updatedAt: '2026-09-29T10:30:00Z',
  },
  {
    id: 'kpi-2026-Q3-emp-010',
    period: 'Quý III / 2026',
    employeeId: 'emp-010',
    employeeCode: 'CB10',
    employeeName: 'Hoàng Thị Lan',
    department: 'Phòng Kế toán - Ngân quỹ',
    position: 'Kế toán viên',
    scoreSelf: 85,
    scoreManager: null,
    scoreChairman: null,
    finalScore: null,
    classification: null,
    status: 'pending_manager',
    selfNotes: 'Đã hoàn thành các bút toán hạch toán ngày và đối chiếu sổ phụ.',
    managerNotes: '',
    chairmanNotes: '',
    updatedAt: '2026-10-01T08:30:00Z',
  },
];

// ============================================================================
// 7. DỮ LIỆU BỎ PHIẾU QUY HOẠCH MẪU (EVALUATIONS_PLANNING)
// ============================================================================
export const INITIAL_PLANNING_VOTES = [
  {
    id: 'vote-001',
    voterId: 'emp-007',
    voterName: 'Trịnh Đức Anh',
    voterRole: 'chairman',
    candidateId: 'emp-003',
    candidateName: 'Nguyễn Văn Sơn',
    currentPosition: 'UV HĐQT - Giám đốc',
    department: 'Ban Điều hành',
    proposedRole: 'Chủ tịch Hội đồng Quản trị',
    vote: 'Tín nhiệm cao',
    comments: 'Đồng chí có phẩm chất đạo đức tốt, năng lực điều hành xuất sắc, có uy tín cao trong toàn đơn vị.',
    createdAt: '2026-09-20T15:00:00Z',
  },
  {
    id: 'vote-002',
    voterId: 'emp-003',
    voterName: 'Nguyễn Văn Sơn',
    voterRole: 'manager',
    candidateId: 'emp-002',
    candidateName: 'Nguyễn Thị Mến',
    currentPosition: 'Kế toán trưởng',
    department: 'Phòng Kế toán - Ngân quỹ',
    proposedRole: 'Phó Giám đốc phụ trách Kế toán - Kho quỹ',
    vote: 'Tín nhiệm cao',
    comments: 'Am hiểu sâu nghiệp vụ tài chính, thanh khoản và quản lý rủi ro ngân quỹ.',
    createdAt: '2026-09-21T09:40:00Z',
  },
  {
    id: 'vote-003',
    voterId: 'emp-007',
    voterName: 'Trịnh Đức Anh',
    voterRole: 'chairman',
    candidateId: 'emp-005',
    candidateName: 'Nguyễn Hữu Nhân',
    currentPosition: 'CB tín dụng',
    department: 'Phòng Tín dụng',
    proposedRole: 'Trưởng phòng Tín dụng',
    vote: 'Tín nhiệm cao',
    comments: 'Năng động, phẩm chất liêm chính, sâu sát địa bàn cơ sở.',
    createdAt: '2026-09-22T14:10:00Z',
  },
];
