// Danh mục dữ liệu chuẩn hóa: Nhân sự, Phòng ban, Luân chuyển công tác & Tiêu chí Đánh giá Tín nhiệm
// Áp dụng cho Quỹ Tín Dụng Nhân Dân Yên Thọ (Thanh Hóa)

export const DEPARTMENTS = [
  'Ban Quản trị (HĐQT)',
  'Ban Điều hành',
  'Ban Kiểm soát',
  'Phòng Tín dụng',
  'Phòng Kế toán - Ngân quỹ',
];

export const ROLES = {
  STAFF: 'staff',
  MANAGER: 'manager',
  CHAIRMAN: 'chairman',
};

export const ROLE_LABELS = {
  [ROLES.STAFF]: 'Cán bộ',
  [ROLES.MANAGER]: 'Ban điều hành',
  [ROLES.CHAIRMAN]: 'Chủ tịch HĐQT',
};

// ============================================================================
// 1. DANH MỤC 10 TIÊU CHÍ ĐÁNH GIÁ TÍN NHIỆM CHUẨN MỰC
// ============================================================================
export const TRUST_CRITERIA = [
  {
    id: 1,
    code: 'TC01',
    group: 'Phẩm chất đạo đức',
    title: '1. Tinh thần trách nhiệm & Đạo đức nghề nghiệp',
    description: 'Tận tụy với công việc, trung thực, có tinh thần trách nhiệm cao, giữ gìn và phát huy uy tín thương hiệu của Quỹ.',
    maxScore: 10,
    minScore: 0,
  },
  {
    id: 2,
    code: 'TC02',
    group: 'Tuân thủ pháp luật & Quy chế',
    title: '2. Chấp hành Quy chế, Nội quy & Pháp luật NHNN',
    description: 'Nghiêm túc tuân thủ quy trình tín dụng, kế toán, an toàn kho quỹ và các văn bản chỉ đạo của Ngân hàng Nhà nước.',
    maxScore: 10,
    minScore: 0,
  },
  {
    id: 3,
    code: 'TC03',
    group: 'Năng lực chuyên môn',
    title: '3. Năng lực chuyên môn & Nghiệp vụ chuyên sâu',
    description: 'Nắm vững quy trình nghiệp vụ, xử lý hồ sơ nhanh chóng, chuẩn xác, hạn chế tối đa sai sót rủi ro vận hành.',
    maxScore: 10,
    minScore: 0,
  },
  {
    id: 4,
    code: 'TC04',
    group: 'Văn hóa giao dịch',
    title: '4. Tác phong giao dịch & Văn hóa phục vụ thành viên',
    description: 'Ân cần, niềm nở, lịch thiệp khi tiếp xúc thành viên và khách hàng vay/gửi vốn, không quan liêu, hách dịch.',
    maxScore: 10,
    minScore: 0,
  },
  {
    id: 5,
    code: 'TC05',
    group: 'Xây dựng tập thể',
    title: '5. Tinh thần đoàn kết & Phối hợp phòng ban',
    description: 'Tương trợ đồng nghiệp, phối hợp nhịp nhàng giữa Tín dụng, Kế toán, Kiểm soát và Ban điều hành.',
    maxScore: 10,
    minScore: 0,
  },
  {
    id: 6,
    code: 'TC06',
    group: 'Kỷ luật & Bảo mật',
    title: '6. Kỷ luật giờ giấc & Bảo mật thông tin tài chính',
    description: 'Chấp hành thời giờ làm việc, bảo quản tài liệu lưu trữ, giữ bí mật tuyệt đối số dư tiền gửi và hồ sơ khách hàng.',
    maxScore: 10,
    minScore: 0,
  },
  {
    id: 7,
    code: 'TC07',
    group: 'Đổi mới & Cải tiến',
    title: '7. Đổi mới sáng tạo & Chuyển đổi số',
    description: 'Chủ động làm chủ phần mềm quản lý, ứng dụng công nghệ trong tác nghiệp, có giải pháp cải tiến hiệu quả.',
    maxScore: 10,
    minScore: 0,
  },
  {
    id: 8,
    code: 'TC08',
    group: 'Liêm chính tài chính',
    title: '8. Liêm chính tài chính & Phòng ngừa rủi ro đạo đức',
    description: 'Minh bạch tiền tệ, tuyệt đối không vòi vĩnh chi phí ngoài quy định, không thông đồng trục lợi tín dụng.',
    maxScore: 10,
    minScore: 0,
  },
  {
    id: 9,
    code: 'TC09',
    group: 'Phong trào đơn vị',
    title: '9. Đóng góp phong trào & Văn hóa tổ chức',
    description: 'Nhiệt tình tham gia các hoạt động an sinh xã hội, phong trào công đoàn, xây dựng đơn vị vững mạnh.',
    maxScore: 10,
    minScore: 0,
  },
  {
    id: 10,
    code: 'TC10',
    group: 'Kết quả công tác',
    title: '10. Hiệu quả hoàn thành chỉ tiêu công việc',
    description: 'Hoàn thành và hoàn thành vượt mức các chỉ tiêu được giao về dư nợ, huy động vốn, kiểm soát nợ quá hạn.',
    maxScore: 10,
    minScore: 0,
  },
];

// ============================================================================
// 2. DANH MỤC KỲ / ĐỢT ĐÁNH GIÁ TÍN NHIỆM
// ============================================================================
export const EVALUATION_PERIODS = [
  {
    id: 'PERIOD-2026-Q3',
    name: 'Đánh giá tín nhiệm Quý III / 2026',
    year: 2026,
    quarter: 3,
    votingMode: 'OPTIONAL', // 'ANONYMOUS_ONLY' | 'IDENTIFIED_ONLY' | 'OPTIONAL'
    status: 'ACTIVE',
    startDate: '2026-09-15',
    endDate: '2026-10-15',
  },
  {
    id: 'PERIOD-2026-Q4',
    name: 'Đánh giá tín nhiệm & Thi đua Quý IV / 2026',
    year: 2026,
    quarter: 4,
    votingMode: 'ANONYMOUS_ONLY', // Bỏ phiếu kín 100%
    status: 'UPCOMING',
    startDate: '2026-12-01',
    endDate: '2026-12-31',
  },
];

// ============================================================================
// 3. HỒ SƠ CÁN BỘ NHÂN VIÊN CHI TIẾT (EMPLOYEES / USERS)
// ============================================================================
export const INITIAL_EMPLOYEES = [
  {
    id: 'emp-001',
    code: 'CB01',
    name: 'Lê Đình Hải',
    gender: 'Nam',
    birthDate: '1976-08-12',
    cccd: '038076001234',
    email: 'chutich@qtdyentho.vn',
    role: ROLES.CHAIRMAN,
    department: 'Ban Quản trị (HĐQT)',
    position: 'Chủ tịch Hội đồng Quản trị',
    assignedArea: 'Chỉ đạo toàn diện hoạt động Quỹ',
    politicalRole: 'Bí thư Chi bộ',
    education: 'Thạc sĩ Tài chính - Ngân hàng',
    joinDate: '2008-03-01',
    contractType: 'Theo nhiệm kỳ Đại hội',
    status: 'ACTIVE',
    phone: '0912.345.678',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-002',
    code: 'CB02',
    name: 'Trần Thị Mai',
    gender: 'Nữ',
    birthDate: '1981-11-25',
    cccd: '038181005678',
    email: 'quanly@qtdyentho.vn',
    role: ROLES.MANAGER,
    department: 'Ban Điều hành',
    position: 'Giám đốc Điều hành',
    assignedArea: 'Điều hành tác nghiệp kinh doanh & vốn',
    politicalRole: 'Phó Bí thư Chi bộ',
    education: 'Cử nhân Kinh tế Tín dụng',
    joinDate: '2010-06-15',
    contractType: 'Theo nhiệm kỳ bổ nhiệm',
    status: 'ACTIVE',
    phone: '0988.765.432',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-003',
    code: 'CB03',
    name: 'Nguyễn Văn An',
    gender: 'Nam',
    birthDate: '1989-04-10',
    cccd: '038089009876',
    email: 'canbo@qtdyentho.vn',
    role: ROLES.STAFF,
    department: 'Phòng Tín dụng',
    position: 'Cán bộ Tín dụng chính',
    assignedArea: 'Xã Yên Thọ & Cụm Tân Lộc (Quý Lộc)',
    politicalRole: 'Đảng viên, Chi ủy viên',
    education: 'Đại học Tài chính - Doanh nghiệp',
    joinDate: '2015-09-01',
    contractType: 'Không xác định thời hạn',
    status: 'ACTIVE',
    phone: '0977.112.233',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-004',
    code: 'CB04',
    name: 'Hoàng Minh Tuấn',
    gender: 'Nam',
    birthDate: '1992-07-19',
    cccd: '038092003456',
    email: 'tuan.hm@qtdyentho.vn',
    role: ROLES.STAFF,
    department: 'Phòng Tín dụng',
    position: 'Cán bộ Thẩm định',
    assignedArea: 'Thẩm định hồ sơ 3 xã liên kết',
    politicalRole: 'Đoàn viên thanh niên',
    education: 'Đại học Ngân hàng',
    joinDate: '2019-02-15',
    contractType: 'HĐLĐ 3 năm',
    status: 'ACTIVE',
    phone: '0943.556.789',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-005',
    code: 'CB05',
    name: 'Phạm Thị Lan',
    gender: 'Nữ',
    birthDate: '1984-03-30',
    cccd: '038184007890',
    email: 'lan.pt@qtdyentho.vn',
    role: ROLES.STAFF,
    department: 'Phòng Kế toán - Ngân quỹ',
    position: 'Kế toán trưởng',
    assignedArea: 'Quản lý tài chính, kho quỹ & kế toán',
    politicalRole: 'Chủ tịch Công đoàn',
    education: 'Đại học Kế toán - Kiểm toán',
    joinDate: '2012-04-01',
    contractType: 'Không xác định thời hạn',
    status: 'ACTIVE',
    phone: '0936.889.900',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-006',
    code: 'CB06',
    name: 'Bùi Thị Thanh',
    gender: 'Nữ',
    birthDate: '1995-12-05',
    cccd: '038195002468',
    email: 'thanh.bt@qtdyentho.vn',
    role: ROLES.STAFF,
    department: 'Phòng Kế toán - Ngân quỹ',
    position: 'Thủ quỹ kiêm Giao dịch viên',
    assignedArea: 'Giao dịch tiền mặt tại quầy',
    politicalRole: 'Bí thư Chi đoàn thanh niên',
    education: 'Cử nhân Tài chính - Kế toán',
    joinDate: '2020-08-01',
    contractType: 'Không xác định thời hạn',
    status: 'ACTIVE',
    phone: '0915.223.344',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-007',
    code: 'CB07',
    name: 'Vũ Đức Nam',
    gender: 'Nam',
    birthDate: '1980-09-14',
    cccd: '038080001357',
    email: 'nam.vd@qtdyentho.vn',
    role: ROLES.STAFF,
    department: 'Ban Kiểm soát',
    position: 'Trưởng Ban Kiểm soát',
    assignedArea: 'Kiểm soát nội bộ toàn diện',
    politicalRole: 'Chi ủy viên',
    education: 'Đại học Luật Kinh tế',
    joinDate: '2011-01-10',
    contractType: 'Theo nhiệm kỳ Đại hội',
    status: 'ACTIVE',
    phone: '0962.334.455',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
  },
];

// ============================================================================
// 4. QUÁ TRÌNH LUÂN CHUYỂN CÔNG TÁC CỦA CÁN BỘ (WORK_HISTORY)
// ============================================================================
export const INITIAL_WORK_HISTORY = [
  {
    id: 'trans-001',
    employeeId: 'emp-003',
    employeeCode: 'CB03',
    employeeName: 'Nguyễn Văn An',
    decisionNumber: '24/QĐ-HĐQT-2022',
    decisionDate: '2022-08-10',
    effectiveDate: '2022-08-15',
    transferType: 'LUAN_CHUYEN_DINH_KY', // Luân chuyển định kỳ phòng ngừa rủi ro NHNN
    transferTypeLabel: 'Luân chuyển định kỳ địa bàn tín dụng',
    fromDepartment: 'Phòng Tín dụng',
    toDepartment: 'Phòng Tín dụng',
    fromPosition: 'Cán bộ Tín dụng phụ trách Quý Lộc',
    toPosition: 'Cán bộ Tín dụng chính phụ trách Yên Thọ',
    fromAssignedArea: 'Cụm 5 thôn xã Quý Lộc',
    toAssignedArea: 'Toàn địa bàn xã Yên Thọ & Tân Lộc',
    signer: 'Lê Đình Hải (Chủ tịch HĐQT)',
    reason: 'Thực hiện quy định của NHNN về luân chuyển định kỳ cán bộ tín dụng sau 3 năm quản lý địa bàn.',
    handoverStatus: 'DA_BAN_GIAO',
    notes: 'Đã hoàn tất bàn giao 142 hợp đồng tín dụng và hồ sơ thế chấp sang cho đ/c Hoàng Minh Tuấn.',
  },
  {
    id: 'trans-002',
    employeeId: 'emp-003',
    employeeCode: 'CB03',
    employeeName: 'Nguyễn Văn An',
    decisionNumber: '12/QĐ-HĐQT-2018',
    decisionDate: '2018-05-20',
    effectiveDate: '2018-06-01',
    transferType: 'BO_NHIEM',
    transferTypeLabel: 'Bổ nhiệm chức danh',
    fromDepartment: 'Phòng Tín dụng',
    toDepartment: 'Phòng Tín dụng',
    fromPosition: 'Cán bộ Tín dụng tập sự',
    toPosition: 'Cán bộ Tín dụng chính thức',
    fromAssignedArea: 'Tập sự nghiệp vụ',
    toAssignedArea: 'Phụ trách hồ sơ vay vốn xã Quý Lộc',
    signer: 'Lê Đình Hải (Chủ tịch HĐQT)',
    reason: 'Hoàn thành thời gian thử thách, đạt kết quả xuất sắc trong kỳ kiểm tra nghiệp vụ tín dụng.',
    handoverStatus: 'DA_BAN_GIAO',
    notes: 'Bổ nhiệm ngạch cán bộ chuyên môn.',
  },
  {
    id: 'trans-003',
    employeeId: 'emp-005',
    employeeCode: 'CB05',
    employeeName: 'Phạm Thị Lan',
    decisionNumber: '08/QĐ-HĐQT-2020',
    decisionDate: '2020-03-12',
    effectiveDate: '2020-04-01',
    transferType: 'BO_NHIEM',
    transferTypeLabel: 'Bổ nhiệm chức vụ lãnh đạo',
    fromDepartment: 'Phòng Kế toán - Ngân quỹ',
    toDepartment: 'Phòng Kế toán - Ngân quỹ',
    fromPosition: 'Phó Trưởng phòng Kế toán',
    toPosition: 'Kế toán trưởng Quỹ TDND',
    fromAssignedArea: 'Kế toán tổng hợp',
    toAssignedArea: 'Quản lý toàn diện công tác kế toán & ngân quỹ',
    signer: 'Lê Đình Hải (Chủ tịch HĐQT)',
    reason: 'Đạt chuẩn chức danh Kế toán trưởng QTDND theo văn bản phê chuẩn số 412/NHNN-THA của NHNN Chi nhánh tỉnh.',
    handoverStatus: 'DA_BAN_GIAO',
    notes: 'Tiếp nhận bàn giao chứng từ và chữ ký số kế toán trưởng.',
  },
  {
    id: 'trans-004',
    employeeId: 'emp-006',
    employeeCode: 'CB06',
    employeeName: 'Bùi Thị Thanh',
    decisionNumber: '14/QĐ-HĐQT-2023',
    decisionDate: '2023-06-15',
    effectiveDate: '2023-07-01',
    transferType: 'LUAN_CHUYEN_DINH_KY',
    transferTypeLabel: 'Luân chuyển định kỳ vị trí kho quỹ',
    fromDepartment: 'Phòng Kế toán - Ngân quỹ',
    toDepartment: 'Phòng Kế toán - Ngân quỹ',
    fromPosition: 'Giao dịch viên tiền gửi',
    toPosition: 'Thủ quỹ kiêm Giao dịch viên',
    fromAssignedArea: 'Quầy giao dịch tiết kiệm',
    toAssignedArea: 'Quản lý kho tiền & điều quỹ',
    signer: 'Trần Thị Mai (Giám đốc Điều hành)',
    reason: 'Quy chế luân phiên cán bộ ngân quỹ nhằm đảm bảo an toàn tuyệt đối tiền mặt và tài sản bảo đảm.',
    handoverStatus: 'DA_BAN_GIAO',
    notes: 'Kiểm kê bàn giao két sắt và sổ theo dõi kho tiền an toàn 100%.',
  },
  {
    id: 'trans-005',
    employeeId: 'emp-004',
    employeeCode: 'CB04',
    employeeName: 'Hoàng Minh Tuấn',
    decisionNumber: '11/QĐ-HĐQT-2024',
    decisionDate: '2024-03-01',
    effectiveDate: '2024-03-15',
    transferType: 'THAY_DOI_DIA_BAN',
    transferTypeLabel: 'Luân chuyển địa bàn công tác',
    fromDepartment: 'Phòng Tín dụng',
    toDepartment: 'Phòng Tín dụng',
    fromPosition: 'Cán bộ Thẩm định',
    toPosition: 'Cán bộ Thẩm định kiêm Tín dụng địa bàn',
    fromAssignedArea: 'Nội nghiệp thẩm định hồ sơ',
    toAssignedArea: 'Mở rộng thẩm định khách hàng xã Quý Lộc',
    signer: 'Trần Thị Mai (Giám đốc Điều hành)',
    reason: 'Tăng cường nhân sự thẩm định thực địa tài sản thế chấp đất nông nghiệp và phương án kinh doanh.',
    handoverStatus: 'DA_BAN_GIAO',
    notes: 'Bàn giao khu vực thẩm định.',
  },
];

// Danh mục chức danh quy hoạch cán bộ nguồn
export const PLANNING_POSITIONS = [
  'Chủ tịch Hội đồng Quản trị',
  'Thành viên chuyên trách HĐQT',
  'Giám đốc Quỹ TDND',
  'Phó Giám đốc phụ trách Tín dụng',
  'Phó Giám đốc phụ trách Kế toán - Kho quỹ',
  'Trưởng Ban Kiểm soát',
  'Thành viên Ban Kiểm soát',
  'Kế toán trưởng',
  'Trưởng phòng Tín dụng',
];

// ============================================================================
// 5. PHIẾU ĐÁNH GIÁ TÍN NHIỆM MẪU (EVALUATIONS_TRUST) - HỖ TRỢ ẨN DANH / CÔNG KHAI
// ============================================================================
export const INITIAL_TRUST_EVALUATIONS = [
  {
    id: 'trust-001',
    periodId: 'PERIOD-2026-Q3',
    isAnonymous: false, // Bỏ phiếu công khai
    evaluatorId: 'emp-001',
    evaluatorName: 'Lê Đình Hải',
    evaluatorRole: 'chairman',
    targetEmployeeId: 'emp-003',
    targetEmployeeName: 'Nguyễn Văn An',
    targetDepartment: 'Phòng Tín dụng',
    scores: { 1: 9, 2: 9, 3: 9, 4: 10, 5: 9, 6: 9, 7: 8, 8: 10, 9: 9, 10: 9 },
    totalScore: 91,
    classification: 'Xuất sắc',
    notes: 'Cán bộ mẫu mực, hoàn thành vượt mức chỉ tiêu dư nợ 3 xã, quan hệ tốt với chính quyền và thành viên.',
    createdAt: '2026-09-15T09:30:00Z',
  },
  {
    id: 'trust-002',
    periodId: 'PERIOD-2026-Q3',
    isAnonymous: true, // Bỏ phiếu ẩn danh (Kín)
    evaluatorId: 'emp-002',
    evaluatorName: 'Cán bộ Quỹ (Ẩn danh)',
    evaluatorRole: 'Ẩn danh',
    targetEmployeeId: 'emp-005',
    targetEmployeeName: 'Phạm Thị Lan',
    targetDepartment: 'Phòng Kế toán - Ngân quỹ',
    scores: { 1: 9, 2: 9, 3: 10, 4: 8, 5: 9, 6: 10, 7: 8, 8: 10, 9: 8, 10: 9 },
    totalScore: 90,
    classification: 'Xuất sắc',
    notes: 'Kế toán trưởng vững vàng nghiệp vụ, quyết toán tài chính chuẩn chỉ, cân đối thanh khoản an toàn.',
    createdAt: '2026-09-18T14:15:00Z',
  },
  {
    id: 'trust-003',
    periodId: 'PERIOD-2026-Q3',
    isAnonymous: true, // Bỏ phiếu ẩn danh (Kín)
    evaluatorId: 'emp-003',
    evaluatorName: 'Cán bộ Quỹ (Ẩn danh)',
    evaluatorRole: 'Ẩn danh',
    targetEmployeeId: 'emp-004',
    targetEmployeeName: 'Hoàng Minh Tuấn',
    targetDepartment: 'Phòng Tín dụng',
    scores: { 1: 8, 2: 8, 3: 8, 4: 7, 5: 8, 6: 8, 7: 7, 8: 9, 9: 7, 10: 8 },
    totalScore: 78,
    classification: 'Tốt',
    notes: 'Thẩm định hồ sơ chặt chẽ, cần nâng cao tốc độ xử lý trên phần mềm tín dụng.',
    createdAt: '2026-09-22T10:00:00Z',
  },
  {
    id: 'trust-004',
    periodId: 'PERIOD-2026-Q3',
    isAnonymous: false,
    evaluatorId: 'emp-001',
    evaluatorName: 'Lê Đình Hải',
    evaluatorRole: 'chairman',
    targetEmployeeId: 'emp-006',
    targetEmployeeName: 'Bùi Thị Thanh',
    targetDepartment: 'Phòng Kế toán - Ngân quỹ',
    scores: { 1: 9, 2: 9, 3: 8, 4: 9, 5: 8, 6: 9, 7: 7, 8: 10, 9: 8, 10: 8 },
    totalScore: 85,
    classification: 'Tốt',
    notes: 'An toàn kho quỹ tuyệt đối, thái độ với khách hàng niềm nở, trung thực cao.',
    createdAt: '2026-09-25T16:20:00Z',
  },
  {
    id: 'trust-005',
    periodId: 'PERIOD-2026-Q3',
    isAnonymous: true,
    evaluatorId: 'emp-005',
    evaluatorName: 'Cán bộ Quỹ (Ẩn danh)',
    evaluatorRole: 'Ẩn danh',
    targetEmployeeId: 'emp-007',
    targetEmployeeName: 'Vũ Đức Nam',
    targetDepartment: 'Ban Kiểm soát',
    scores: { 1: 9, 2: 10, 3: 9, 4: 8, 5: 8, 6: 10, 7: 8, 8: 10, 9: 8, 10: 9 },
    totalScore: 89,
    classification: 'Tốt',
    notes: 'Kiểm tra độc lập, kịp thời kiến nghị các điểm cần khắc phục trong quy trình.',
    createdAt: '2026-09-28T11:45:00Z',
  },
];

// ============================================================================
// 6. DỮ LIỆU KPI MẪU (EVALUATIONS_KPI)
// ============================================================================
export const INITIAL_KPI_EVALUATIONS = [
  {
    id: 'kpi-001',
    period: 'Quý III / 2026',
    employeeId: 'emp-003',
    employeeName: 'Nguyễn Văn An',
    department: 'Phòng Tín dụng',
    position: 'Cán bộ Tín dụng chính',
    scoreSelf: 92,
    scoreManager: 90,
    scoreChairman: 94,
    finalScore: 92.0,
    status: 'completed',
    selfNotes: 'Hoàn thành 110% chỉ tiêu tăng trưởng dư nợ Quý 3, không phát sinh nợ quá hạn mới.',
    managerNotes: 'Đánh giá cao nỗ lực bám sát các thôn bản và xử lý hồ sơ chu đáo.',
    chairmanNotes: 'Thống nhất xếp loại thi đua mức cao nhất quý này.',
    updatedAt: '2026-09-30T17:00:00Z',
  },
  {
    id: 'kpi-002',
    period: 'Quý III / 2026',
    employeeId: 'emp-005',
    employeeName: 'Phạm Thị Lan',
    department: 'Phòng Kế toán - Ngân quỹ',
    position: 'Kế toán trưởng',
    scoreSelf: 88,
    scoreManager: 92,
    scoreChairman: 90,
    finalScore: 89.8,
    status: 'completed',
    selfNotes: 'Báo cáo NHNN đúng hạn, hạch toán chính xác 100%, bảo đảm thanh khoản.',
    managerNotes: 'Quản trị dòng vốn hiệu quả, chi trả lương và huy động nhịp nhàng.',
    chairmanNotes: 'Hoàn thành xuất sắc nhiệm vụ.',
    updatedAt: '2026-09-30T17:10:00Z',
  },
  {
    id: 'kpi-003',
    period: 'Quý III / 2026',
    employeeId: 'emp-004',
    employeeName: 'Hoàng Minh Tuấn',
    department: 'Phòng Tín dụng',
    position: 'Cán bộ Thẩm định',
    scoreSelf: 85,
    scoreManager: 80,
    scoreChairman: null,
    finalScore: null,
    status: 'pending_chairman',
    selfNotes: 'Đã thẩm định 45 hồ sơ vay vốn, tỷ lệ hồ sơ hợp lệ đạt 98%.',
    managerNotes: 'Cần chú ý đối soát thực địa các tài sản bảo đảm là đất nông nghiệp.',
    chairmanNotes: '',
    updatedAt: '2026-10-02T10:15:00Z',
  },
  {
    id: 'kpi-004',
    period: 'Quý III / 2026',
    employeeId: 'emp-006',
    employeeName: 'Bùi Thị Thanh',
    department: 'Phòng Kế toán - Ngân quỹ',
    position: 'Thủ quỹ kiêm Giao dịch viên',
    scoreSelf: 86,
    scoreManager: null,
    scoreChairman: null,
    finalScore: null,
    status: 'pending_manager',
    selfNotes: 'Thu chi tiền mặt khớp số liệu 100%, phục vụ 650 lượt giao dịch an toàn.',
    managerNotes: '',
    chairmanNotes: '',
    updatedAt: '2026-10-05T08:30:00Z',
  },
];

// ============================================================================
// 7. DỮ LIỆU BỎ PHIẾU QUY HOẠCH MẪU (EVALUATIONS_PLANNING)
// ============================================================================
export const INITIAL_PLANNING_VOTES = [
  {
    id: 'vote-001',
    voterId: 'emp-001',
    voterName: 'Lê Đình Hải',
    voterRole: 'chairman',
    candidateId: 'emp-003',
    candidateName: 'Nguyễn Văn An',
    currentPosition: 'Cán bộ Tín dụng chính',
    department: 'Phòng Tín dụng',
    proposedRole: 'Phó Giám đốc phụ trách Tín dụng',
    vote: 'Tín nhiệm cao',
    comments: 'Đồng chí có phẩm chất đạo đức tốt, có năng lực chỉ đạo mảng tín dụng cơ sở, uy tín cao trong tập thể.',
    createdAt: '2026-09-20T15:00:00Z',
  },
  {
    id: 'vote-002',
    voterId: 'emp-002',
    voterName: 'Trần Thị Mai',
    voterRole: 'manager',
    candidateId: 'emp-003',
    candidateName: 'Nguyễn Văn An',
    currentPosition: 'Cán bộ Tín dụng chính',
    department: 'Phòng Tín dụng',
    proposedRole: 'Phó Giám đốc phụ trách Tín dụng',
    vote: 'Tín nhiệm cao',
    comments: 'Rất nhất trí, đồng chí An năng động, trách nhiệm và có năng lực quy tụ nhân sự.',
    createdAt: '2026-09-21T09:40:00Z',
  },
  {
    id: 'vote-003',
    voterId: 'emp-001',
    voterName: 'Lê Đình Hải',
    voterRole: 'chairman',
    candidateId: 'emp-005',
    candidateName: 'Phạm Thị Lan',
    currentPosition: 'Kế toán trưởng',
    department: 'Phòng Kế toán - Ngân quỹ',
    proposedRole: 'Phó Giám đốc phụ trách Kế toán - Kho quỹ',
    vote: 'Tín nhiệm cao',
    comments: 'Am hiểu sâu nghiệp vụ tài chính tiền tệ, bảo đảm an toàn hệ thống.',
    createdAt: '2026-09-22T14:10:00Z',
  },
  {
    id: 'vote-004',
    voterId: 'emp-002',
    voterName: 'Trần Thị Mai',
    voterRole: 'manager',
    candidateId: 'emp-004',
    candidateName: 'Hoàng Minh Tuấn',
    currentPosition: 'Cán bộ Thẩm định',
    department: 'Phòng Tín dụng',
    proposedRole: 'Trưởng phòng Tín dụng',
    vote: 'Tín nhiệm',
    comments: 'Cán bộ trẻ có nhiệt huyết, cần thêm thời gian thử thách rèn luyện bản lĩnh quản lý.',
    createdAt: '2026-09-24T16:30:00Z',
  },
];
